# Workflow Code: HackCostume_v1    DO NOT REMOVE
# Purpose:
#     This workflows is used to create team-specific jira tickets when a Pull Request is opened in its repository
#
# Frequency:
#    - This workflow should only be used once per repository
#
# Projects to use this Template with:
#    - Any repository where the team would like a Jira ticket to be created when a Pull Request is created in it
#
# Important:
#    Before committing changes be sure to replace the values:
#    - <REPO_NAME>
#    - <PLATFORM_JIRA_TEAM>
#    - <ORG_NAME>

name: Create Ticket when PR is created in <REPO_NAME> Repository

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: [main]

jobs:
  Create-Ticket-For-Pr:
    runs-on: im-linux
    steps:
    - name: Call and Run PR Ticket Creator
      uses: im-platform/pr-ticket-creator/.github/actions/pr-ticket-creator@main
      with:
        git_api_token: ${{ secrets.GITHUB_TOKEN }}
        jira_assigned_team: "<PLATFORM_JIRA_TEAM>"
        jira_components: ""
        jira_password: "${{ secrets.JIRA_PASSWORD_TICKET_CREATOR }}"
        jira_url: "${{ secrets.JIRA_URL }}"
        jira_username: "${{ vars.JIRA_USERNAME_TICKET_CREATOR }}"
        pipeline_bot_pat: "${{ secrets.PIPELINE_BOT_PAT }}"
        pr_author: "${{ github.event.pull_request.user.login }}"
        pr_number: "${{ github.event.pull_request.number }}"
        pr_repo: "<ORG_NAME>/<REPO_NAME>"
        pr_title: "${{ github.event.pull_request.title }}"
        pr_url: "${{ github.event.pull_request.html_url }}"
        sendgrid_key: "${{ secrets.SENDGRID_KEY }}"
